FROM public.ecr.aws/lambda/python:3.9

COPY pyproject.toml ${LAMBDA_TASK_ROOT}/
COPY *.py ${LAMBDA_TASK_ROOT}/

WORKDIR ${LAMBDA_TASK_ROOT}
RUN pip install --upgrade pip
RUN pip install poetry
RUN poetry config virtualenvs.create false --local
RUN poetry install

ENTRYPOINT ["pytest"]
