FROM public.ecr.aws/lambda/python:3.9

COPY *.py ${LAMBDA_TASK_ROOT}/
COPY staticfiles ${LAMBDA_TASK_ROOT}/staticfiles
COPY requirements.txt ${LAMBDA_TASK_ROOT}

WORKDIR ${LAMBDA_TASK_ROOT}
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt

ENTRYPOINT ["pytest"]
