FROM public.ecr.aws/lambda/python:3.9

RUN mkdir /app
COPY pyproject.toml /app
COPY ./ /app/

WORKDIR /app
RUN pip install --upgrade pip
RUN pip install poetry
RUN poetry config virtualenvs.create false --local
RUN poetry install

ENTRYPOINT ["pytest"]
