service: trowel

frameworkVersion: '3'

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./

package:
  individually: true
  exclude:
    - ./**

functions:
  generate-terraform:
    image: ${env:AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/trowel-lambda:latest
    timeout: 20
    name: trowel-generate-terraform