service: trowel

frameworkVersion: '3'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  ecr:
    images:
      appimage:
        path: ./

package:
  individually: true
  exclude:
    - ./**

functions:
  generate-terraform:
    image: ${env:AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/trowel-lambda-${env:STAGE_NAME}:${env:RELEASE_VERSION}
    timeout: 20
    url: true

