name: Unit Tests
on: [push]
jobs:
  bdd-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run terraform-compliance
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install
          chmod +x bdd.bash
          ./bdd.bash
